services:
  ph803w2-mqtt-bridge:
    container_name: ph803w2-mqtt-bridge
    image: topale707/ph803w2-mqtt-bridge:latest
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - TZ=${TZ}
